### ISSUE TITLE
Pasting isn't working

### ISSUE THREAD

**Issue by winzig** [lionsharecapital/lionshare-desktop#25]
Tried to paste the number of coins I hold, and didn't work, had to type in the amount.

Also, it might be good to support more than two decimal points. Not that it impacts the value of the coin too much, necessarily, but for the purpose of being able to keep track of exactly what I have.

**Comment by jorilallo** [comment]
Fixed this in #27. Decimal points is definitely a bug, I just need to think a bit how to fix that so I'll file another issue for that.
