### ISSUE TITLE
Portfolio currencies save

### ISSUE THREAD

**Issue by dib258** [lionsharecapital/lionshare-desktop#33]
Hi,

I added in my Portfolio few currencies. Then I changed to only one and a different value. Each time I change the tab (Portfolio -> Prices) or quit the app, when I return I get the old values.

Is there any kind of save ?

**Comment by ztnark** [comment]
I believe https://github.com/lionsharecapital/lionshare-desktop/issues/36 is a duplicate of this issue.

**Comment by maksim-s** [comment]
Fixed by https://github.com/lionsharecapital/lionshare-desktop/pull/39
