### ISSUE TITLE
yarn fails with permission denied

### ISSUE THREAD

**Issue by sgehrman** [lionsharecapital/lionshare-desktop#61]
I'm on Windows, just got it and tried running yarn...

npm install also failed with a similar error

$ yarn
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone ssh://git@github.com/prettier/prettier.git C:\Users\Steve\AppData\Local\Yarn\cache\.tmp\998d9289033d5404a23434d3979d79dc
Directory: f:\Github\lionshare-desktop
Output:
Cloning into 'C:\Users\Steve\AppData\Local\Yarn\cache\.tmp\998d9289033d5404a23434d3979d79dc'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by jorilallo** [comment]
I feel like this is something related to your environment as we're not doing anything special with yarm. You can always use `npm` over `yarn` as well

**Comment by bediaz** [comment]
I had to open the package.json file and change this line
`   "prettier": "git+ssh://git@github.com/prettier/prettier.git",`

to this:
`"prettier": "git+https://git@github.com/prettier/prettier.git",`
